### ISSUE TITLE
Rename `learn` function

### ISSUE THREAD

**Issue by EronWright** [nupic-community/flink-htm#10]
The `learn` function that **flink-htm** adds to `DataStream` is the primary API that inserts HTM into a dataflow graph.    I consider the name of the function to be an open issue, since `learn` has another meaning in an HTM context.

The function name must be a verb, similar to existing functions like `map`, `filter`, and `groupBy`.   

I suggest that the function name be `grok`.

Old:

```
val anomalyScores = env
      .addSource(nycTraffic)
      .keyBy("streamId")
      .learn(network)
      .select(...)
```

New:

```
val anomalyScores = env
      .addSource(nycTraffic)
      .keyBy("streamId")
      .grok(network)
      .select(...)
```

**Comment by cogmission** [comment]
Another suggestion could be infer() or simply compute()?

**Comment by rhyolight** [comment]
I think `grok` is an already overloaded term in Numenta history. I prefer `compute`.

**Comment by EronWright** [comment]
I think `compute` is too generic; any library could be said to compute.  Let's sit on this for a while then.

**Comment by rhyolight** [comment]
`setupHtm()`

**Comment by EronWright** [comment]
I'm looking for a word that would fit into this sentence:  "I _filtered_ the stream then I _blahed_ the stream."

My latest suggestion is `analyze`.

**Comment by rhyolight** [comment]
I like `analyze` the best so far.

**Comment by EronWright** [comment]
Maybe we should leave this as-is.
