### ISSUE TITLE
Support Flink Checkpointing of HTM State

### ISSUE THREAD

**Issue by EronWright** [nupic-community/flink-htm#2]
Flink's reliability is based on checkpointing of operator state.    In **flink-htm** the critical state is that of the HTM network.  

The operator code is well-prepared to support checkpointing.   A state holder is allocated from Flink (see [L63 of KeyedHTMInferenceOperator](https://github.com/nupic-community/flink-htm/blob/a11f12b5389410a6db08e83e2ecb2f881e493fff/flink-htm-streaming-java/src/main/java/org/numenta/nupic/flink/streaming/api/operator/KeyedHTMInferenceOperator.java#L65)) into which the network instance is stored.   Flink expects to use the serializer passed to it, and will automatically serialize the network at the appropriate time.     The issue is that the network is not actually serializable (as of htm.java 0.6.5), and the job will crash if checkpointing is enabled.

Stretch goal:  Flink supports both synchronous and asynchronous checkpointing.   In the latter case, the operator is free to process elements while the state is being checkpointed.   Depending on how the network state is ultimately checkpointed, consider it.

**Comment by cogmission** [comment]
@EronWright I have finished my other work and I'm returning to the Serialization work now. I will try and get this done in the next week so we can move on...

**Comment by EronWright** [comment]
Update: thanks to @cogmission, work is proceeding on supporting serialization of the network object (for checkpointing purposes) and of the inference object (as output of the HTM operator).

**Comment by EronWright** [comment]
With #15, checkpointing seems to work.    Some additional tests will be written before this issue is closed.

**Comment by rhyolight** [comment]
Great job, you two!

**Comment by EronWright** [comment]
This is done.
