### ISSUE TITLE
Support network 'reset'

### ISSUE THREAD

**Issue by EronWright** [nupic-community/flink-htm#8]
It is possible to send a `reset` to HTM to indicate that a temporal sequence has ended.   Investigate how to facilitate a reset in the flink-htm API.

A simple option would be to expose the network object to direct manipulation in the `select` function.   But I would rather a more filter-like approach like `HTMStream::resetOn(f: ResetFunction)`.

Is it better to reset before or after an event?

**Comment by cogmission** [comment]
Numenta convention is for reset to apply to the new corresponding data. So... before...
Example: 

Sunday, 1
Monday, 0
Tuesday, 0
Wednesday, 0
Thursday, 0
Friday, 0
Saturday, 0
Sunday, 1

Where "1" is interpreted as true etc. This is how the underlying Sensors work.

**Comment by EronWright** [comment]
Based on the feedback, the approach should be that the reset function is called _before_ the event is processed.  If possible we should support a _stateful_ reset function, to facilitate the _after_ use case.

_Before_ use case which reads as "reset if it is Sunday":

```
stream.learn(network).resetOn(evt => evt.isSunday).select(...)
```

_After_ use case which reads as, "if it is Saturday, remember to reset on the next event":

```
stream.learn(network).resetOnWithState((evt,prior) => (prior, evt.isSaturday)).select(...)
```

**Comment by cogmission** [comment]
Also, please keep in mind that there is an issue to devise a functionality whereby the "isLearn" flag can be set independently on algorithms within a Layer.
https://github.com/numenta/htm.java/issues/314

**Comment by EronWright** [comment]
A snippet of the API that was implemented:

```
    env
      .addSource(new DayDemoRecordSourceFunction(1, false))
      .learn(new DayDemoNetworkFactory)
      .resetOn(input => input.dayOfWeek == 0)
      .select(inference => (inference._1.dayOfWeek, inference._2.getAnomalyScore))
      .print()
```
